version: "3"



services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER="$OPENVPN_USER"
      - OPENVPN_PASSWORD="$OPENVPN_PASSWORD"
      # Timezone for accurate log times
      - TZ=Europe/Kyiv
      # Server list updater
      - UPDATER_PERIOD=0
      - UPDATER_MIN_RATIO=0.0001
      - SERVER_COUNTRIES=Ukraine
      - FIREWALL_DEBUG=True
      - FIREWALL_OUTBOUND_SUBNETS="$bi2_subnet"

  app:
    container_name: vizok-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./user_dir_1:/app/user_dir_1
      - ./user_dir_2:/app/user_dir_2
      - ./user_dir_3:/app/user_dir_3
      - ./user_dir_4:/app/user_dir_4
      - ./user_dir_5:/app/user_dir_5
      - ./user_dir_6:/app/user_dir_6
      - ./user_dir_7:/app/user_dir_7
      - ./user_dir_8:/app/user_dir_8
      - /logs/:/logs/GoogleShop/
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
