version: "3"

services:
  app-limit:
    container_name: vizok-app-limit
    build:
      context: ./
      dockerfile: ./Limit.dockerfile
    cap_add:
      - NET_ADMIN
    ports:
      - 8889:8888/tcp # HTTP proxy
      - 8389:8388/tcp # Shadowsocks
      - 8389:8388/udp # Shadowsocks
      - 81:80/udp
      - 81:80/tcp
    volumes:
        - /dev/net/tun:/dev/net/tun
        - /logs/:/logs/GoogleShop/
        - ./user_dir_1:/app/user_dir_1
        - ./user_dir_2:/app/user_dir_2
        - ./user_dir_3:/app/user_dir_3
        - ./user_dir_4:/app/user_dir_4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
      - net.ipv6.conf.eth0.disable_ipv6=1

      
  app-all:
    container_name: vizok-app-all
    build:
      context: ./
      dockerfile: ./All.dockerfile
    cap_add:
      - NET_ADMIN
    ports:
      - 8890:8888/tcp # HTTP proxy
      - 8390:8388/tcp # Shadowsocks
      - 8390:8388/udp # Shadowsocks
      - 82:80/udp
      - 82:80/tcp
    volumes:
        - /dev/net/tun:/dev/net/tun
        - /logs/:/logs/GoogleShop/
        - ./user_dir_5:/app/user_dir_5
        - ./user_dir_6:/app/user_dir_6
        - ./user_dir_7:/app/user_dir_7
        - ./user_dir_8:/app/user_dir_8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
      - net.ipv6.conf.eth0.disable_ipv6=1


  promtail:
    image: grafana/promtail:latest
    volumes:
      - /logs/:/var/logs  # Mount the host logs folder to the container
      - ./promtail-config.yml:/etc/promtail/config.yml  # Mount the Promtail configuration
    command: -config.file=/etc/promtail/config.yml

