server:
 http_listen_port: 9080
 grpc_listen_port: 0

positions:
 filename: /tmp/positions.yaml

clients:
 - url: http://10.0.101.111/loki/loki/api/v1/push

scrape_configs:
 - job_name: python-logs
   static_configs:
     - targets:
         - localhost
       labels:
         job: varlogs
         parser: regex
         __path__: /var/logs/*.log